### ISSUE TITLE
form and listing

### ISSUE THREAD

**Issue by reyk-zepper** [reyk-zepper/atlantis-capstone#1]
## Value Proposition

As a  user i want to save my products of a project with their prices and shown them in a list below so that i have an overview of all products with there total cost each project
​
## Description

![Screenshot 2023-03-19 at 15 29 45](https://user-images.githubusercontent.com/117449040/226182780-bef5acb2-b710-4f87-bcb1-7b302c993a25.png)

## Acceptance Criteria

- [x] i can save each product with it price for one project
- [x] the projects are listed below with teir total costs each
     ​
## Tasks

- [x] build a entry form to save each product of an project with it individual price
- [x] the price entry should only accepted numbers
- [x] each project should be stored in its own card component below -create card component with .map?
- [x] the card component should display all products with their prices and the total costs of an project
      ​
