### ISSUE TITLE
UserStory6- EditPage

### ISSUE THREAD

**Issue by reyk-zepper** [reyk-zepper/atlantis-capstone#10]
## Value Proposition

**As a** User
**I want to** edit projects on seperate page
**so that**  i have a better overview while editing
​

## Description

![Screenshot 2023-03-28 at 16 41 42](https://user-images.githubusercontent.com/117449040/228275185-c4d49618-b6a0-4ef3-bd82-f156d9142653.png)

​

## Acceptance Criteria

- [x] when you click the edit button you enter the editFormPage
- [x] when you click the back button in the editFormPage, you get back to ActivePage
- [x] when you click delete on EditPage project get deleteted
- [x] when you click the save button in the EditPage form get submitted
      ​

## Tasks

- [x] create dynamic routes for EditPage
- [x] Add Navigation component
- [x] Add push route to save and delete button
      ​

## Complexity

S
