### ISSUE TITLE
UserStory7-  ProjectDetailsPage

### ISSUE THREAD

**Issue by reyk-zepper** [reyk-zepper/atlantis-capstone#11]
## Value Proposition

**As a**  User
**I want to** click the ProjectsOverviewCard to see the details page of an project
**so that** i can see more informations to the project
​

## Description

![Screenshot 2023-03-28 at 16 50 43](https://user-images.githubusercontent.com/117449040/228278093-fb26c97b-c7d6-42f2-94ee-693f5ee80f18.png)
design or text)
​

## Acceptance Criteria

- [x] when you click on the ActiveProjectsOverviewCard you get routed to the detailViewPage
- [x] display ]project name and total price in OverviewProjectCard
- [x] clicking OverviewProjectCard roots to details page
      ​

## Tasks

- [x] implement dynamic routing to DetailViewPage
- [x] create OverviewProjectCards component
- [x] simple styling
      ​

## Complexity

M
