### ISSUE TITLE
userStory8 - donePage

### ISSUE THREAD

**Issue by reyk-zepper** [reyk-zepper/atlantis-capstone#14]
## Value Proposition

**As a** User
**I want to**  move my active project to a done page
**so that**  i have an overview over my done projects
​

## Description

![Screenshot 2023-03-31 at 13 00 48](https://user-images.githubusercontent.com/117449040/229103106-2fdd7d31-e8e0-4344-b3ae-3e123681efde.png)

## Acceptance Criteria

- [x] clicking done in the edit page moves project to the done page
- [x] on the done page a project overview card is displayed
- [x] clicking the overviwe card routes to done details page 
      ​

## Tasks

- [x] create donePage
- [x] create DoneDetailsPage dynamic
- [x] creates button to move active to done page
      ​

## Complexity

M
