### ISSUE TITLE
userStory MongoDB

### ISSUE THREAD

**Issue by reyk-zepper** [reyk-zepper/atlantis-capstone#15]
## Value Proposition

**As a** User 
**I want to** save my projects persistently 
**so that** excess my projects from everywhhere
​

## Description
no visual changes only backend

- MongoDB
- Mongoose
- API
- fetch
- CRUD
​

## Acceptance Criteria

- [ ] all projects from the database are dispalyed
- [ ] create s new prject in the database
- [ ] update existing project in database
- [ ] delete project from the database
      ​

## Tasks

- [ ] create database on MongoDB Atlas
- [ ] prepare database connesation
- [ ] create database CRUD functions
- [ ] create API endpoints
- [ ] map over fetched projects
      ​

## Complexity

XL
