### ISSUE TITLE
userStory - localStorage

### ISSUE THREAD

**Issue by reyk-zepper** [reyk-zepper/atlantis-capstone#19]
## Value Proposition

**As a** User
**I want to** store my projects persist
**so that**  i don't lose them when i reload the page
​

## Description

- implement local storage
- no visual changes
​

## Acceptance Criteria

- [x] the projects should be stored persistently
      ​

## Tasks

- [x] implement local storage
- [x] minimal styling with styled components
      ​

## Complexity

S
