### ISSUE TITLE
edit and delete

### ISSUE THREAD

**Issue by reyk-zepper** [reyk-zepper/atlantis-capstone#2]
## Value Proposition

**As a**  User
**I want to** edit or delete my projects
**so that** i can change the prices, product or delete the project
​

## Description

![Screenshot 2023-03-19 at 19 38 18](https://user-images.githubusercontent.com/117449040/226199409-ca55e686-31e5-4015-ab0d-f990fc5e7c0f.png)

## Acceptance Criteria

- [ ] i can edit the saved projects
- [ ] i can delete the saved projects
      ​

## Tasks

- [ ] create a button component
- [ ] use the button component  and implement a function to start editing an existing project
- [ ] use the button component  and implement a function delete an existing project when it is in editing mode
- [ ] the delete button should only appear when editing mode is on
      ​

## Complexity
