### ISSUE TITLE
userStory - productPicture

### ISSUE THREAD

**Issue by reyk-zepper** [reyk-zepper/atlantis-capstone#25]
## Value Proposition

**As a** User 
**I want to** have the possibility to add a product-picture to the project
**so that** i can show the builded product
​

## Description

![Screenshot 2023-04-06 at 14 27 10](https://user-images.githubusercontent.com/117449040/230378858-096a55c8-ab68-4b06-98bc-fbd081c20f1e.png)
​

## Acceptance Criteria

- [ ] there is button to add a picture in the editForm
      ​

## Tasks

- [ ] add a button to import a product-picture
- [ ] the product-picture is shown on details page
- [ ] simple styling
      ​

## Complexity

S

**Comment by nikokreissl** [comment]
Nice idea! 😊
As you already mentioned in the value proposition and on tasks you want to show the image on the details. Maybe you can copy and paste this information to acceptance criteria too that the user needs to switch to the details page in order to see the uploaded image.
Can a user remove / replace the image once uploaded? Maybe a short sentence about this would make it more clear for the person doing the QA 😊

**Comment by reyk-zepper** [comment]
thx for your hints i implement it🙌🏻
