### ISSUE TITLE
userStory - Timer

### ISSUE THREAD

**Issue by reyk-zepper** [reyk-zepper/atlantis-capstone#26]
## Value Proposition

**As a** User  
**I want to**  to capture the time i spend working on a pc-build
**so that** i can see the total working time for a project 
​

## Description

![Screenshot 2023-04-11 at 11 25 42](https://user-images.githubusercontent.com/117449040/231116798-79b3f0e1-0c4b-48cc-9114-f9b717e3a3d4.png)

## Acceptance Criteria

- [x] there is a button in the editForm to record the working time
- [x] the user can click the timer itself to start and stop it
- [x] the time is displayed
      ​

## Tasks

- [x] add a button to start and stop recording the working-time
- [x] display the working-time
- [x] styling
      ​

## Complexity

M

**Comment by nikokreissl** [comment]
Also here a little bit more information on acceptance criteria would be good IMO - just based on the design I would guess the timer is also the button, right? If so a short addition "User can click the timer itself to start and stop the timer" would be good to make it even more clear 🙂
Other than that great US and a really nice idea! 🚀

**Comment by reyk-zepper** [comment]
thx a lot...i implement it
