### ISSUE TITLE
userStory - export to PDF

### ISSUE THREAD

**Issue by reyk-zepper** [reyk-zepper/atlantis-capstone#27]
## Value Proposition

**As a** User
**I want to** export my project to pdf
**so that** i can simply print it
​

## Description

![Screenshot 2023-04-06 at 14 27 39](https://user-images.githubusercontent.com/117449040/230393662-b2c7b340-0ea3-4283-96b4-f77c63770f75.png)
​

## Acceptance Criteria

- [ ] there is a button to export the done project to PDF
- [ ] the button is only shown in the doneDetailsPage
      ​

## Tasks

- [ ] add a button to export project to PDF
- [ ] styling
      ​

## Complexity

S

**Comment by nikokreissl** [comment]
Great design! 😊
Maybe you can add a little bit more details to the acceptance criteria like what happens when the user clicks the button. Will there be a notification when the export has started, ended, where the file can be found etc.
And at value proposition maybe instead of "...I can simply export it" something like "...I can share it easily" or similar is more reasonable 🙂

**Comment by reyk-zepper** [comment]
hej nico, yes you are right...ma problem, for now i don't know exactly what will happen beacuse i don't have a look on export to pdf functions until yet, but i will add it to the tasks to make it more clear
