### ISSUE TITLE
userStory - Delete

### ISSUE THREAD

**Issue by reyk-zepper** [reyk-zepper/atlantis-capstone#29]
## Value Proposition

**As a** User
**I want to** remove entrys from the edit form 
**so that** i can delete pc-parts i don't need to use
​

## Description

![Screenshot 2023-04-10 at 18 10 13](https://user-images.githubusercontent.com/117449040/230943185-10badfe7-dc9e-47db-8486-6fa5ba3fe925.png)

​

## Acceptance Criteria

- [x] in the editForm is the possibillity to delete the entrys
- [x] there is an x-button on each entry you added before to delete
      ​

## Tasks

- [x] add a delete button on each entry in the edit form
- [x] implement the deletion process on click for each of this buttons in each entry
- [x] styling
      ​

## Complexity

S

**Comment by Sascha-Pionczewski** [comment]
LGTM
