### ISSUE TITLE
userStory - charts

### ISSUE THREAD

**Issue by reyk-zepper** [reyk-zepper/atlantis-capstone#3]
## Value Proposition

**As a** User
**I want to** see the costs of an project in relation to each other
**so that** i have an overview about the final costs and how they composed
​

## Description
![Screenshot 2023-03-19 at 19 54 53](https://user-images.githubusercontent.com/117449040/226200661-e45f84b7-bcf5-4c85-a2ee-b7f3c33b1b10.png)

## Acceptance Criteria

- [x] in the overviewCard a pie chart is displayed with project data
- [x] in the detailsPage is a barchart is displayed with the pie chart data
      ​

## Tasks

- [x] create a pie chart component 
- [x] charts should be created with each project data indidually based on the entrydata
- [x] research chart.js
- [x] prepare data for charts
      ​

## Complexity
XL
