### ISSUE TITLE
nav bar & header

### ISSUE THREAD

**Issue by reyk-zepper** [reyk-zepper/atlantis-capstone#4]
## Value Proposition

**As a** User
**I want to** have my active projects seperated from the entry form
**so that** i have more structere and a better overview

## Description

![Screenshot 2023-03-19 at 20 20 42](https://user-images.githubusercontent.com/117449040/226203787-9a59633d-8f94-48e4-a224-ab0505f36f25.png)
​

## Acceptance Criteria

- [x] the entry form and the active products are seperated from each other
- [x] there is a navigation bar to change between form and projects
- [x] there is a header component with a placeholder as logo
- [x] the header and navigation component should be shown on both sides
      ​

## Tasks

-  [x] seperate the active projects from the entry form
-  [x] create a navigation bar component
-  [x] create header component
-  [x] implement them on each side and make them work

      ​

## Complexity
