### ISSUE TITLE
UserStory5-landing page and navigations

### ISSUE THREAD

**Issue by reyk-zepper** [reyk-zepper/atlantis-capstone#8]
## Value Proposition

**As a** User
**I want to** have an oranized overview
**so that** i can better navigate through the pages 
​

## Description

![userStory5](https://user-images.githubusercontent.com/117449040/227958609-9707972a-269e-4bc0-8b7b-37058c2a751d.png)

## Acceptance Criteria

- [X] Plus button to create a new project is displayed on the HomePage
- [X] Homepage Navigation is displayed with
- - Home Link
- - Active Link 
      ​

## Tasks

- [X] create AddProject
- [X] create two different navigation components
- [X] maove add project form to the new AddProjectPage
- [X] add push route to the submit button
- [X] add button to route to the new AddProjectPage on the Homepage​

## Complexity

M
